#include <stdio.h>
#include "./src/simple_polynomial_regression/simple_polynomial_regression.h"
#include "src/csv_reader/csv_reader.h"
#include "src/utils/utils.h"
#include <math.h>

/**
 * Predict a value. Expects matrix and degree.
 * @param n
 * @param degree
 * @param arr
 * @param x_pred
 * @return
 */
float polynomial_predict(int n, int degree, float *arr, float x_pred);
/**
 * Test and prints the mean error of the function generated by data.
 * @param n
 * @param degree
 * @param arr
 */
void test_values(int n, int degree, float *arr);

int main() {
    int degree = 2, average = 1;
    float x_pred = 3.6528;
    char file_name[50] = "csv_4555.csv";

//    printf("Please, write the name of the file to get data: ");
//    scanf("%s", file_name);

    Data_ dt = read_csv(file_name);
//
//    printf("Select your degree: ");
//    scanf("%i", &degree);
//
//
//    printf("Do you want to test average error, or get the result?:\n");
//    printf("[0] Average Error of coefficients.\n");
//    printf("[1] Get the predicted Result.\n");
//    scanf("%i", &average);
//

    if (average == 0) {
        test_values(dt.i, degree,  &dt.dot[0][0]);
    } else {
        printf("Now write your X value:\n");
        scanf("%f", &x_pred);
        float pred = polynomial_predict(dt.i, degree, &dt.dot[0][0], x_pred);
        printf("Your predicted value is: %.2f", pred);
    }
    printf("\n");
    return 0;
}

float polynomial_predict(int n, int degree, float *arr, float x_pred) {
    int coef_size = degree + 1;
    float coef[coef_size];
    find_coefficients(n, arr, degree, coef);
    return predict(coef_size, coef, x_pred);
 }

void test_values(int n, int degree, float *arr) {
    int coef_size = degree + 1;
    float coefficients[coef_size], results[n], real_x = 0, predicted_y = 0, real_y = 0, sum = 0;

    find_coefficients(n, arr, degree, coefficients);

    printf("The coefficients generated by this data are:\n");
    print_arr(coefficients, coef_size);
    printf("\n\n");

    for (int i = 0; i < n; ++i) {
        real_x = get_from_flattened_matrix(i, 0, 1,arr);
//        real_x = arr[i][0];
        real_y = get_from_flattened_matrix(i, 1, 1, arr);
//        real_y = arr[i][1];
        predicted_y = predict(coef_size, coefficients, real_x);

        sum += (float) fabs(real_y - predicted_y);
        results[i] = sum;
    }
    printf("Your average Error is: %.2f", sum/n);
}
